-- Question: Calculate the total revenue generated by each airline.
SELECT A.Airline_Name, SUM(T.Price) as Total_Revenue
FROM
    Airlines A
    JOIN Flights F ON A.Airline_ID = F.Airline_ID
    JOIN Tickets T ON F.Flight_ID = T.Flight_ID
GROUP BY
    A.Airline_Name;