CREATE TABLE Instructors (
    InstructorID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Email VARCHAR(100),
    DeptID INT,
    FOREIGN KEY (DeptID) REFERENCES Departments (DeptID)
);

INSERT INTO
    Instructors (
        InstructorID,
        FirstName,
        LastName,
        Email,
        DeptID
    )
VALUES (
        1,
        'John',
        'Smith',
        'john.smith@univ.edu',
        1
    ),
    (
        2,
        'Jane',
        'Doe',
        'jane.doe@univ.edu',
        2
    ),
    (
        3,
        'Robert',
        'Brown',
        'robert.brown@univ.edu',
        3
    ),
    (
        4,
        'Emily',
        'Davis',
        'emily.davis@univ.edu',
        1
    ),
    (
        5,
        'Michael',
        'Wilson',
        'michael.wilson@univ.edu',
        4
    ),
    (
        6,
        'Sarah',
        'Johnson',
        'sarah.johnson@univ.edu',
        5
    ),
    (
        7,
        'David',
        'Lee',
        'david.lee@univ.edu',
        6
    ),
    (
        8,
        'Jennifer',
        'White',
        'jennifer.white@univ.edu',
        7
    ),
    (
        9,
        'James',
        'Harris',
        'james.harris@univ.edu',
        8
    ),
    (
        10,
        'Linda',
        'Martin',
        'linda.martin@univ.edu',
        9
    ),
    (
        11,
        'William',
        'Thompson',
        'william.thompson@univ.edu',
        10
    ),
    (
        12,
        'Elizabeth',
        'Garcia',
        'elizabeth.garcia@univ.edu',
        11
    ),
    (
        13,
        'Richard',
        'Martinez',
        'richard.martinez@univ.edu',
        12
    ),
    (
        14,
        'Barbara',
        'Robinson',
        'barbara.robinson@univ.edu',
        13
    ),
    (
        15,
        'Joseph',
        'Clark',
        'joseph.clark@univ.edu',
        14
    ),
    (
        16,
        'Susan',
        'Rodriguez',
        'susan.rodriguez@univ.edu',
        15
    ),
    (
        17,
        'Thomas',
        'Lewis',
        'thomas.lewis@univ.edu',
        16
    ),
    (
        18,
        'Jessica',
        'Walker',
        'jessica.walker@univ.edu',
        17
    ),
    (
        19,
        'Charles',
        'Hall',
        'charles.hall@univ.edu',
        18
    ),
    (
        20,
        'Mary',
        'Allen',
        'mary.allen@univ.edu',
        19
    ),
    (
        21,
        'Christopher',
        'Young',
        'christopher.young@univ.edu',
        20
    ),
    (
        22,
        'Patricia',
        'Hernandez',
        'patricia.hernandez@univ.edu',
        10
    ),
    (
        23,
        'Daniel',
        'King',
        'daniel.king@univ.edu',
        1
    ),
    (
        24,
        'Nancy',
        'Wright',
        'nancy.wright@univ.edu',
        2
    ),
    (
        25,
        'Matthew',
        'Lopez',
        'matthew.lopez@univ.edu',
        16
    );