CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Email VARCHAR(100),
    EnrollmentDate DATE,
    Major VARCHAR(50)
);

INSERT INTO
    Students (
        StudentID,
        FirstName,
        LastName,
        Email,
        EnrollmentDate,
        Major
    )
VALUES (
        1,
        'Alice',
        'Smith',
        'alice.smith@student.edu',
        '2023-09-01',
        'Computer Science'
    ),
    (
        2,
        'Bob',
        'Johnson',
        'bob.johnson@student.edu',
        '2023-09-01',
        'Mathematics'
    ),
    (
        3,
        'Charlie',
        'Williams',
        'charlie.williams@student.edu',
        '2022-09-01',
        'Physics'
    ),
    (
        4,
        'David',
        'Brown',
        'david.brown@student.edu',
        '2023-09-01',
        'Chemistry'
    ),
    (
        5,
        'Eve',
        'Jones',
        'eve.jones@student.edu',
        '2021-09-01',
        'Biology'
    ),
    (
        6,
        'Frank',
        'Garcia',
        'frank.garcia@student.edu',
        '2023-09-01',
        'History'
    ),
    (
        7,
        'Grace',
        'Miller',
        'grace.miller@student.edu',
        '2022-09-01',
        'English'
    ),
    (
        8,
        'Hannah',
        'Davis',
        'hannah.davis@student.edu',
        '2024-09-01',
        'Psychology'
    ),
    (
        9,
        'Ivy',
        'Rodriguez',
        'ivy.rodriguez@student.edu',
        '2023-09-01',
        'Economics'
    ),
    (
        10,
        'Jack',
        'Martinez',
        'jack.martinez@student.edu',
        '2022-09-01',
        'Business'
    ),
    (
        11,
        'Kevin',
        'Hernandez',
        'kevin.hernandez@student.edu',
        '2023-09-01',
        'Art History'
    ),
    (
        12,
        'Liam',
        'Lopez',
        'liam.lopez@student.edu',
        '2024-09-01',
        'Music'
    ),
    (
        13,
        'Mia',
        'Gonzalez',
        'mia.gonzalez@student.edu',
        '2023-09-01',
        'Political Science'
    ),
    (
        14,
        'Noah',
        'Wilson',
        'noah.wilson@student.edu',
        '2022-09-01',
        'Sociology'
    ),
    (
        15,
        'Olivia',
        'Anderson',
        'olivia.anderson@student.edu',
        '2023-09-01',
        'Philosophy'
    ),
    (
        16,
        'Paul',
        'Thomas',
        'paul.thomas@student.edu',
        '2021-09-01',
        'Engineering'
    ),
    (
        17,
        'Quinn',
        'Taylor',
        'quinn.taylor@student.edu',
        '2023-09-01',
        'Architecture'
    ),
    (
        18,
        'Rose',
        'Moore',
        'rose.moore@student.edu',
        '2022-09-01',
        'Nursing'
    ),
    (
        19,
        'Sam',
        'Jackson',
        'sam.jackson@student.edu',
        '2024-09-01',
        'Education'
    ),
    (
        20,
        'Tina',
        'Martin',
        'tina.martin@student.edu',
        '2023-09-01',
        'Environmental Science'
    ),
    (
        21,
        'Ursula',
        'Lee',
        'ursula.lee@student.edu',
        '2022-09-01',
        'Astronomy'
    ),
    (
        22,
        'Victor',
        'Perez',
        'victor.perez@student.edu',
        '2023-09-01',
        'Statistics'
    ),
    (
        23,
        'Wendy',
        'Thompson',
        'wendy.thompson@student.edu',
        '2021-09-01',
        'Linguistics'
    ),
    (
        24,
        'Xander',
        'White',
        'xander.white@student.edu',
        '2024-09-01',
        'Anthropology'
    ),
    (
        25,
        'Yara',
        'Harris',
        'yara.harris@student.edu',
        '2023-09-01',
        'Theology'
    );